ln -s "$HOME/.dotfiles/shell/zsh/.zshrc" "$HOME/.zshrc"
ln -s "$HOME/.dotfiles/git/.gitconfig" "$HOME/.gitconfig"
ln -s "$HOME/.dotfiles/editors/nvim" "$HOME/.config/nvim"
ln -s "$HOME/.dotfiles/bin/bat/config" "$HOME/.config/bat/config"
ln -s "$HOME/.dotfiles/git/.gitignore_global" "$HOME/.gitignore_global"
ln -s "$HOME/.dotfiles/bin/rofi" "$HOME/.config/rofi"
ln -s "$HOME/.dotfiles/system/Xorg/.xinitrc" "$HOME/.xinitrc"