ln -s "$HOME/.dotfiles/shell/zsh/.zshrc" "$HOME/.zshrc"
ln -s "$HOME/.dotfiles/git/.gitconfig" "$HOME/.gitconfig"
ln -s "$HOME/.dotfiles/editors/nvim" "$HOME/.config/nvim"
ln -s "$HOME/.dotfiles/bin/bat/config" "$HOME/.config/bat/config"
ln -s "$HOME/.dotfiles/bin/tldr/.tldrrc" "$HOME/.tldrrc"
