
[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "/home/fabrizio/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 50
  max_selection_size_bytes = 0
  static_history = [
    '''
**Rama**
**Archivos modificados**
**¿Como probarla?**
**Pasos para subir**
Copiar los archivos modificados en su lugar en producción y borrar caché.
''',
'''
/* ####################################################################################################################
NAME
######################################################################################################################*/
'''
  ]
  trim_space_from_selection = true
  use_primary_selection_as_input = false
